import { capitol, laurel, columnMark, flourish, starRule } from '../icons.js';

/**
 * Masthead: wordmark, nav, seal, and the twin rules with the column medallion
 * that separate the masthead from the page body.
 */
class SiteHeader extends HTMLElement {
  connectedCallback() {
    const current = this.getAttribute('current') || '';
    const links = [
      ['/bills', 'Bills', 'bills'],
      ['/alignment', 'Political Alignment', 'alignment'],
      ['/about', 'About', 'about'],
    ];
    this.innerHTML = `
      <header class="masthead">
        <div class="masthead__inner shell">
          <a class="wordmark" href="/">
            <span class="wordmark__mark">${capitol(38)}</span>
            <span class="wordmark__text">
              <span class="wordmark__name">AI Vote Tracker</span>
              <span class="wordmark__tagline">Understand. Compare. Stay informed.</span>
            </span>
          </a>
          <nav class="masthead__nav" aria-label="Primary">
            ${links
              .map(
                ([href, label, key]) =>
                  `<a href="${href}" class="nav-link${key === current ? ' is-current' : ''}"${
                    key === current ? ' aria-current="page"' : ''
                  }>${label}</a>`
              )
              .join('')}
          </nav>
          <span class="masthead__seal">${laurel(58)}</span>
        </div>
      </header>
      <div class="masthead-rules" aria-hidden="true">
        <div class="masthead-rules__line masthead-rules__line--thick"></div>
        <div class="masthead-rules__line"></div>
        <span class="masthead-rules__medallion">${columnMark(24)}</span>
      </div>`;
  }
}

class SiteFooter extends HTMLElement {
  connectedCallback() {
    this.innerHTML = `
      <footer class="site-footer">
        <div class="shell">
          <div class="site-footer__ornament" aria-hidden="true">
            <span class="rule"></span>
            <span class="site-footer__mark">${capitol(26)}</span>
            <span class="rule"></span>
          </div>
          <p class="site-footer__note">
            AI Vote Tracker &middot; verdicts are generated by language models and are not endorsements.
          </p>
          <p class="site-footer__meta">
            Built by <a href="https://x.com/pwnies" rel="noopener">Jacob Miller</a>
            &middot; design created with <a href="https://diffui.ai" rel="noopener">diffui.ai</a>
          </p>
        </div>
      </footer>`;
  }
}

/** Eyebrow + display headline + star rule + standfirst. */
class PageMasthead extends HTMLElement {
  connectedCallback() {
    const eyebrow = this.getAttribute('eyebrow') || '';
    const title = this.getAttribute('title') || '';
    const lead = this.getAttribute('lead') || '';
    const size = this.getAttribute('size') === 'hero' ? 'page-head__title--hero' : '';
    this.innerHTML = `
      <div class="page-head">
        ${eyebrow ? `<p class="eyebrow">${eyebrow}</p>` : ''}
        <h1 class="page-head__title ${size}">${title}</h1>
        <div class="page-head__rule" aria-hidden="true">${starRule(140)}</div>
        ${lead ? `<p class="page-head__lead">${lead}</p>` : ''}
      </div>`;
  }
}

/** Centred small-caps section heading bracketed by laurel flourishes. */
class SectionHeading extends HTMLElement {
  connectedCallback() {
    const label = this.getAttribute('label') || '';
    this.innerHTML = `
      <div class="section-heading">
        <span class="section-heading__flourish" aria-hidden="true">${flourish('left', 44)}</span>
        <h2 class="section-heading__label">${label}</h2>
        <span class="section-heading__flourish" aria-hidden="true">${flourish('right', 44)}</span>
      </div>`;
  }
}

customElements.define('site-header', SiteHeader);
customElements.define('site-footer', SiteFooter);
customElements.define('page-masthead', PageMasthead);
customElements.define('section-heading', SectionHeading);
